// list actions
export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';

// edit form actions
export const SET_EDIT_MODE_FOR_SERVICE = 'SET_EDIT_MODE_FOR_SERVICE';
export const SET_PRICE_FOR_EDITED_SERVICE = 'SET_PRICE_FOR_EDITED_SERVICE';
export const SET_NAME_FOR_EDITED_SERVICE = 'SET_NAME_FOR_EDITED_SERVICE';
export const RESET_EDIT_FORM = 'RESET_EDIT_FORM';

// filter
export const SET_FILTER = 'SET_FILTER';
